config/routes.rb
Bigblockdeals::Application.routes.draw do

  resources :widget_types

  # This is for the Basic pages and their edit pages
  BASIC_CONTROLLERS.each do |f|
      get "#{f.last[:url].to_sym}/(:format)", :controller => "basics", :action => "#{f.first}", :as => f.last[:url]
      get "admin/#{f.last[:url].to_sym}/edit/(:id)(:format)", :controller => "basic_edits", :action => "#{f.first}", :as => "#{f.first}_edit"
      match "admin/#{f.last[:url].to_sym}/create/(:id)(:format)", :controller => "basic_edits", :action => "#{f.first}_create", :as => "#{f.first}_create"
  end
  match "business_inquires" => "business_leads#index"
  match "/business_leads/index" => "business_leads#index"

  root :to => "basics#current_deals"


  # This is for all the Good Reads
    get '/bbd-blog/' => "good_reads#index", :as => 'bbd_blog'
    get '/admin/bbd-blog/manage' => "good_reads#manage", :as => 'manage_bbd_blog'
    get '/admin/bbd-blog/new' => "good_reads#new", :as => "new_good_read"
    get '/admin/bbd-blog/:id/edit' => "good_reads#edit", :as => "edit_good_read"
    get '/bbd-blog/category/:id', :controller => 'good_reads', :action => 'show_categories', :as => "good_reads_category"
    match "/bbd-blog/date" => redirect("/bbd-blog") 
    get '/bbd-blog/date/(:year(/:month))', :controller => 'good_reads', :action => 'show_dates', :as => "good_reads_date"
    resources :good_reads
    
  # This is for all the Quotes

    
    scope "admin" do
      resources :quotes, :as => "quotes"
      resources :widgets, :as => "widgets"
      match 'widgets/move_dim_widgets' => 'widgets#move_dim_widgets', :as => :move_dim_widgets
      resources :categories, :as => "categories"
      resources :sessions, :as => "sessions"
      resources :spreadsheets, :as => "spreadsheets"
      resources :affiliates, :as => "affiliates"
      match 'affiliates/csv_import' => 'affiliates#csv_import'
      resources :customer_details, :as => 'customer_details'
      match 'customer_details/csv_import' => 'customer_details#csv_import'
      match 'widgets/manage' => 'widgets#index', :as => "manage_widgets"
      # resources :business_leads, :as => "business_leads"
    end
    
  #this is for all the Catagories for the good reads

  # This is for the Administration usage.
    resources :admins
    
  # This is for loggin in and out
    get '/admin/login' => 'sessions#new', :as => "login"
    get '/admin/logout' => 'sessions#destroy', :as => "logout"
    get "/admin/business_lead/:id" => "business_leads#show", :as => "admin_business_lead"
    get "/admin/business_leads/" => "business_leads#show_all", :as => "admin_business_leads"
    match '/admin/business_leads/destroy/:id' => 'business_leads#destroy'
    
end

app/models/widget.rb
=begin
  TODO Add in validations.
  TODO Change Sizes of the Images
=end

class Widget < ActiveRecord::Base
  attr_accessible :text_1, :title, :text_2, :bottom_title, :widget_image, :image_delete, :widgetable_id, :widgetable_type, :good_read_active, :contact_active, :about_us_active, :current_deal_active, :recent_deal_active, :privacy_policy_active, :for_business_active, :terms_of_service_active, :good_read_order, :contact_order, :about_us_order, :current_deal_order, :recent_deal_order, :privacy_policy_order, :for_business_order, :terms_of_service_order
  has_attached_file :widget_image, :styles => { :mini => "300x300>", :side_bar => "200x>" }


  before_save :destroy_image?

  def image_delete
    @image_delete ||= "0"
  end

  def image_delete=(value)
    @image_delete = value
  end

  private
    def destroy_image?
      self.widget_image.clear if @image_delete == "1"
    end

end
# == Schema Information
#
# Table name: widgets
#
#  id                        :integer         not null, primary key
#  text_1                    :text
#  title                     :string(255)
#  text_2                    :text
#  bottom_title              :string(255)
#  widget_image_file_name    :string(255)
#  widget_image_content_type :string(255)
#  widget_image_file_size    :integer
#  widget_image_updated_at   :datetime
#  created_at                :datetime
#  updated_at                :datetime
#  widgetable_id             :integer
#  widgetable_type           :string(255)
#  good_read_active          :boolean
#  contact_active            :boolean
#  about_us_active           :boolean
#  current_deal_active       :boolean
#  recent_deal_active        :boolean
#  privacy_policy_active     :boolean
#  for_business_active       :boolean
#  terms_of_service_active   :boolean
#  good_read_order           :integer
#  contact_order             :integer
#  about_us_order            :integer
#  current_deal_order        :integer
#  recent_deal_order         :integer
#  privacy_policy_order      :integer
#  for_business_order        :integer
#  terms_of_service_order    :integer
#

app/controllers/widgets_controller.rb
class WidgetsController < ApplicationController
  
  uses_tiny_mce(:options => {
    :theme => 'advanced',
    :height => '220',
    :width => '100%',
    :theme_advanced_buttons1 => "bold,italic,underline,separator,strikethrough,justifyleft,justifycenter,justifyright,justifyfull,separator,bullist,numlist,",
    :theme_advanced_buttons2 => "link, unlink, spellchecker,separator,sub,sup,image",
    :theme_advanced_buttons3 => "",
    :plugins => %w{contextmenu paste spellchecker},
    :spellchecker_languages => "+English=en",
  })
  
  def index
    @widgets = Widget.all
    @layout = 'full-width'
  end
  
  def new
    @widget = Widget.new
  end
  
  def create
    @widget = Widget.new(params[:widget])
    if @widget.valid?
      @widget.save
      redirect_to widgets_path, :notice => "Your widget was saved." # Laudie frickin dah!"
    else  
      render "new"
    end
  end
  
  def show
    @widget = Widget.all
    @page = "good_read"
  end
  
  def edit
    @widget = Widget.find(params[:id])
  end
  
  def update
    @widget = Widget.find(params[:id])
    if @widget.update_attributes(params[:widget])
      if params[:widget][:image_delete] == true
        @widget.image_delete
        @widget.save
      end
      redirect_to widgets_path, :notice => "Changes saved!"
    else
      render "edit"
    end
  end
  
  def move_dim_widgets
    @layout = "edit-page"
    # TODO Update the widgets
    arr = params[:order]
    array = []
    arr.each do |f|
      array << f.split(",")
    end
    @split = array
    array.each do |f|
      @widget = Widget.find(f[0])
      @widget.current_deal_order = f[1].to_i
      @widget.save
    end
      
      # Widget.where("? = current_deal_active", true ).update_all(["current_deal_order = ?", 2])
    # redirect_to root_path, :notice => "Changes Saved!"
    
  end
  
  
  def destroy
    @widget = Widget.find(params[:id])
    @widget.destroy
    redirect_to manage_widgets_path, :notice => "Your Widget has been deleted."
  end
  
end

app/helpers/widgets_helper.rb
module WidgetsHelper
  
  def active(model_obj)
    arr = []
    if model_obj.good_read_active == true
      arr << "Good Reads"
    end
    if model_obj.contact_active == true
      arr << "Contacts"
    end
    if model_obj.about_us_active == true
      arr << "About Us"
    end
    if model_obj.current_deal_active == true
      arr << "Current Deal"
    end
    if model_obj.recent_deal_active == true
      arr << "Recent Deals"
    end
    if model_obj.privacy_policy_active == true
      arr << "Privacy Policy"
    end
    if model_obj.for_business_active == true
      arr << "For Business"
    end
    if model_obj.terms_of_service_active == true
      arr << "Terms of Service"
    end
    if arr.empty?
      arr = ["None"]
    end
      return arr
  end
  
end

app/views/widgets/_form.html.erb
<%= form_for @widget, :html => { :multipart => true } do |f| %>


<div class="full-width-clearer">
	<%= f.select :widgetable_type, options_for_select([['Twitter', 'twitter'], ['Custom', 'custom'], ['Facebook', 'facebook'], ['Mail Chimp', 'mailchimp']], :selected => :widgetable_type) %>
</div>



<div class="full-width-clearer">
	<%= f.label :text_1, "Video Embed Code - BE SURE TO SET THE WIDTH TO 200PX IN THE EMBED CODE!!" %>
   	<div class="widget-iframe">
   		<%= f.text_area :text_1 %>
   	</div>
</div>	

<div class="full-width-clearer">
	<div class="half-width-box">
		<div class="full-width-clearer">
			<%= f.label :title, "Widget Title Text" %>
		   	<%= f.text_field :title %>   
		</div>
		<div class="full-width-clearer">
			<%= f.label :bottom_title, "Minor Title" %>
			<%= f.text_field :bottom_title %>
		</div>
	</div>
	<div class="full-width-clearer">
		<%= f.label :text_2, "Main widget text" %>
		<%= f.text_area :text_2, :class => "mceEditor" %>	
	</div>
</div>   	

<div class="full-width-clearer">
	<a href="http://bbd-images.bigblockdeals.com/image-manager" target="blank">Manage Images</a>
</div>

<div class="full-width-clearer">
	<p class="full-width-clearer">Active Pages:</p>
	<div class="active-page-checkbox">
		<%= f.label :about_us_active, "About Us" %>
		<%= f.check_box :about_us_active, :class => "checkbox" %>
	</div>
	<div class="active-page-checkbox">
		<%= f.label :contact_active, "Contact" %>
		<%= f.check_box :contact_active, :class => "checkbox" %>
	</div>
	<div class="active-page-checkbox">
		<%= f.label :current_deal_active, "Current Deal" %>
		<%= f.check_box :current_deal_active, :class => "checkbox" %>
	</div>
	<div class="active-page-checkbox">
		<%= f.label :recent_deal_active, "Recent Deal" %>
		<%= f.check_box :recent_deal_active, :class => "checkbox" %>		
	</div>
	<div class="active-page-checkbox">
		<%= f.label :privacy_policy_active, "Privacy Policy" %>
		<%= f.check_box :privacy_policy_active, :class => "checkbox" %>		
	</div>
	<div class="active-page-checkbox">
		<%= f.label :for_business_active, "For Business" %>
		<%= f.check_box :for_business_active, :class => "checkbox" %>		
	</div>
	<div class="active-page-checkbox">
		<%= f.label :terms_of_service_active, "Terms Of Service" %>
		<%= f.check_box :terms_of_service_active, :class => "checkbox" %>		
	</div>
	
</div>

<div class="full-width-clearer">
	<%= f.submit "Submit", :disable_with => 'Submitting...' %>
</div>
<% end %>

app/views/widgets/edit.html.erb
<div class="edit-page">
	<div class="topper"></div>
	<div class="main-content">
		<h2>Edit Widget</h2>

		<%= render :partial => 'form' %>

	</div>
	<div class="bottom"></div>
</div>

app/views/widgets/index.html.erb
<div class='edit-page-wide'>
	<h2>All Dem Widgets</h2>
		<%= link_to "New Widget", new_widget_path, :class => 'full-width-clearer' %>
		<div class="all-widget-previews">
			<% @widgets.each do |w| %>
				<div class="widget-preview">
					<div class="full-width-clearer">
						<% unless w.text_1 == nil || w.text_1.empty? %>
							<%= w.text_1.html_safe %>
						<% end %>
					</div>
					<% if w.widget_image_file_name %>
						<%= image_tag w.widget_image.url(:side_bar) %>
					<% end %>
					<p class="semi-bold-item full-width-clearer"><%= w.title %></p>
					<% unless w.text_2 == nil%>
						<p class="full-width-clearer"><%= w.text_2.html_safe %></p>
					<% end %>
					<% unless w.bottom_title == nil%>
						<p class="full-width-clearer"><%= w.bottom_title.html_safe %></p>
					<% end %>
					<p class="full-width-clearer">Active Pages: <%= active(w).to_sentence %></p>
					<%= link_to "Edit", edit_widget_path(w.id) %>
					<%= link_to "Delete", { :action => "destroy", :id => w.id }, :confirm => 'Are you sure?', :method => :delete %>
				</div>
			<% end %>
		</div>
</div>

app/views/widgets/move_dim_widgets.html.erb
<h2>Order Saved</h2>
 <!-- <%= params[:order] %>
 
 <%= @split %>
 
 <%= params %> -->

app/views/widgets/new.html.erb
<div class="edit-page">
	<div class="topper"></div>
	<div class="main-content">
		<h2>New Widget</h2>

		<%= render :partial => 'form' %>

		
	</div>
	<div class="bottom"></div>
</div>

app/views/widgets/show.html.erb
<div class="edit-page">
	<div class="topper"></div>
	<div class="main-content">
		
	</div>
	<div class="bottom"></div>
</div>