config/routes.rb
Bigblockdeals::Application.routes.draw do

  resources :widget_types

  # This is for the Basic pages and their edit pages
  BASIC_CONTROLLERS.each do |f|
      get "#{f.last[:url].to_sym}/(:format)", :controller => "basics", :action => "#{f.first}", :as => f.last[:url]
      get "admin/#{f.last[:url].to_sym}/edit/(:id)(:format)", :controller => "basic_edits", :action => "#{f.first}", :as => "#{f.first}_edit"
      match "admin/#{f.last[:url].to_sym}/create/(:id)(:format)", :controller => "basic_edits", :action => "#{f.first}_create", :as => "#{f.first}_create"
  end
  match "business_inquires" => "business_leads#index"
  match "/business_leads/index" => "business_leads#index"

  root :to => "basics#current_deals"


  # This is for all the Good Reads
    get '/bbd-blog/' => "good_reads#index", :as => 'bbd_blog'
    get '/admin/bbd-blog/manage' => "good_reads#manage", :as => 'manage_bbd_blog'
    get '/admin/bbd-blog/new' => "good_reads#new", :as => "new_good_read"
    get '/admin/bbd-blog/:id/edit' => "good_reads#edit", :as => "edit_good_read"
    get '/bbd-blog/category/:id', :controller => 'good_reads', :action => 'show_categories', :as => "good_reads_category"
    match "/bbd-blog/date" => redirect("/bbd-blog") 
    get '/bbd-blog/date/(:year(/:month))', :controller => 'good_reads', :action => 'show_dates', :as => "good_reads_date"
    resources :good_reads
    
  # This is for all the Quotes

    
    scope "admin" do
      resources :quotes, :as => "quotes"
      resources :widgets, :as => "widgets"
      match 'widgets/move_dim_widgets' => 'widgets#move_dim_widgets', :as => :move_dim_widgets
      resources :categories, :as => "categories"
      resources :sessions, :as => "sessions"
      resources :spreadsheets, :as => "spreadsheets"
      resources :affiliates, :as => "affiliates"
      match 'affiliates/csv_import' => 'affiliates#csv_import'
      resources :customer_details, :as => 'customer_details'
      match 'customer_details/csv_import' => 'customer_details#csv_import'
      match 'widgets/manage' => 'widgets#index', :as => "manage_widgets"
      # resources :business_leads, :as => "business_leads"
    end
    
  #this is for all the Catagories for the good reads

  # This is for the Administration usage.
    resources :admins
    
  # This is for loggin in and out
    get '/admin/login' => 'sessions#new', :as => "login"
    get '/admin/logout' => 'sessions#destroy', :as => "logout"
    get "/admin/business_lead/:id" => "business_leads#show", :as => "admin_business_lead"
    get "/admin/business_leads/" => "business_leads#show_all", :as => "admin_business_leads"
    match '/admin/business_leads/destroy/:id' => 'business_leads#destroy'
    
end

app/models/good_read.rb
=begin
  TODO Add associations with quotes
    I believe the best course of action here would be to go ahead and create a join model just for this one. The rest will stay the same.
=end

class GoodRead < ActiveRecord::Base
  attr_accessible :post, :title, :category_id, :image, :image_delete
  validates_presence_of :post, :title, :category, :message => "can't be blank"
  validates_length_of :title, :within => 3..30, :message => "must be between 3 and 30 characters"
  belongs_to :category
  

# Relates to the images
  has_attached_file :image, 
    :styles => { :thumb => "100x100>", :medium => "315x315>" },
    :storage => :s3, 
    :bucket => 'bigblockdeals',
    :s3_credentials => S3_CREDENTIALS
  validates_attachment_size :image, :less_than => 5.megabytes
  validates_attachment_content_type :image, :content_type => ['image/jpeg', 'image/png']
  
    before_save :destroy_image?
    
    def image_delete
      @image_delete ||= "0"
    end

    def image_delete=(value)
      @image_delete = value
    end

  private
    def destroy_image?
      self.image.clear if @image_delete == "1"
    end
end

# == Schema Information
#
# Table name: good_reads
#
#  id                 :integer         not null, primary key
#  title              :string(255)
#  post               :text
#  created_at         :datetime
#  updated_at         :datetime
#  category_id        :integer
#  image_file_name    :string(255)
#  image_content_type :string(255)
#  image_file_size    :integer
#  image_updated_at   :datetime
#


# == Schema Information
#
# Table name: good_reads
#
#  id                 :integer         not null, primary key
#  title              :string(255)
#  post               :text
#  created_at         :datetime
#  updated_at         :datetime
#  category_id        :integer
#  image_file_name    :string(255)
#  image_content_type :string(255)
#  image_file_size    :integer
#  image_updated_at   :datetime
#

app/controllers/good_reads_controller.rb
class GoodReadsController < ApplicationController
  before_filter :bomb_dot_com, :except => [:index, :show, :show_categories, :show_dates]
  uses_tiny_mce(:options => {
    :theme => 'advanced',
    :height => '420',
    :width => '100%',
    :theme_advanced_buttons1 => "bold,italic,underline,separator,strikethrough,justifyleft,justifycenter,justifyright,justifyfull,separator,bullist,numlist,outdent,indent,separator,cut,copy,paste,undo,redo,cleanup",
    :theme_advanced_buttons2 => "link, unlink, spellchecker, removeformat,formatselect,fontsizeselect,separator,sub,sup,forecolor,backcolor,forecolorpicker,backcolorpicker,image",
    :theme_advanced_buttons3 => "",
    :plugins => %w{contextmenu paste spellchecker},
    :spellchecker_languages => "+English=en",
  })
  
  def index
    @posts = GoodRead.order("created_at DESC").page(params[:page]).per(5)
    @title = "BBD Blog"
    @page = "good_read"
    @categories = gather_thine_categories
    @dates = gather_thine_dates
    @layout = "blog"
    @widgets = Widget.where("? = good_read_active", true).order(:good_read_order)
  end
  
  def manage
    @posts = GoodRead.order("created_at DESC").all
    @title = "Manage BBD Blog"
    @categories = gather_thine_categories
    @dates = gather_thine_dates
    @layout = "blog"
    @widgets = "No widgets for the Blog"
  end

  def show
    @layout = "blog"
    @post = GoodRead.find(params[:id])
    @title = "BBD Blog | #{@post.created_at.to_s(:good_reads_title)}"
    @widgets = Widget.all
    @page = "good_read"
  end

  def show_categories
    @layout = "blog"
    @category = Category.find_by_name(params[:id])
    @page = "good_read"
    @widgets = Widget.where("? = good_read_active", true).order(:good_read_order)
    @categories = gather_thine_categories
    @dates = gather_thine_dates
    if @category.good_reads.nil?
      redirect_to good_reads_path, :notice => "There is no category named #{params[:id]}"
    else
      @posts = @category.good_reads
    end
  end
  
  # FIXME Move to the model(Needs refactoring)
  def show_dates
    @layout = "blog"
    @widgets = Widget.where("? = good_read_active", true).order(:good_read_order)
    @categories = gather_thine_categories
    @dates = gather_thine_dates
    if params[:year]
      if params[:month]
        @month = "01 #{params[:month]} #{params[:year]}".to_date
        @posts = GoodRead.all(:conditions => ["created_at >= ? AND created_at <= ?", @month.at_beginning_of_month, @month.at_end_of_month])
        render :show_categories
      else
        @year = "01 Jan #{params[:year]}".to_date
        @posts = GoodRead.all(:conditions => ["created_at >= ? AND created_at <= ?", @year.at_beginning_of_year, @year.at_end_of_year])
        render :show_categories
      end
    end
  end
  
  def new
    @post = GoodRead.new
    @title = "BBD Blog | New"
    @categories = Category.list_names
  end

  def create
    @post = GoodRead.new(params[:good_read])
    if @post.save
      redirect_to :bbd_blog, :notice => "Post saved"
    else
      @post.errors.each do |e|
        puts e
      end
      render :new, :alert => "didn't work"
    end
  end

  def edit
    @layout = "blog"
    @post = GoodRead.find(params[:id])
    @title = "BBD Blog | Edit #{@post.created_at.to_s(:good_reads_title)}"
    @categories = gather_thine_categories
  end

  def update
    @layout = "blog"
    @post = GoodRead.find(params[:id])
    if @post.update_attributes(params[:good_read])
      if params[:good_read][:image_delete] == true
        @post.image_delete 
      end
      
      redirect_to :manage_bbd_blog, :notice => "Update Successful"
    else
      render :edit_good_read, :notice => "Update was unsuccessful"
    end
  end
  
  def destroy
    @layout = "blog"
    @post = GoodRead.find(params[:id])
    @post.destroy
    redirect_to :manage_bbd_blog, :notice => "Post Deleted"
  end

  private
    def gather_thine_dates
      @dates = GoodRead.all( :select => "created_at", :order => "created_at" )
    end
    
    def gather_thine_categories
      @categories = Category.find(:all, :order => "name")
    end
end

app/helpers/good_reads_helper.rb
module GoodReadsHelper
  def shorten (string, word_limit = 50)
    words = string.split(/\s/)
    if words.size >= word_limit
      @shortened = words[0,(word_limit-1)].join(" ") + '...'
      @shortened.html_safe
    else 
      string.html_safe
    end
  end
  

end

app/views/good_reads/_categories.html.erb
<!-- Trey don't laugh.... I just did this really quick so it'd be readable -->

	<div class="indiv-widget blog-categories">
		<div class="widget-topper"></div>
		<div class="widget-content">
			<% if @categories.nil? %>
				<h3>NO CATEGORIES YO!</h3>
			<% else %>
				<h3></h3>
				<% @categories.each do |f| %>
					<%= link_to "#{f.name}", :action => "show_categories", :id => f.name %><br>
				<% end %>
			<% end %>
			<% if session[:admin_id] %>
				<br><%= link_to "Manage Categories", categories_path %>
			<% end %>
		</div>
		<div class="widget-bottom"></div>
	</div>

app/views/good_reads/_dates.html.erb
<!-- Trey don't laugh.... I just did this really quick so itd be readable -->


	<div class="indiv-widget blog-dates">
		<div class="widget-topper"></div>
		<div class="widget-content">
			<h3></h3>
			<% @year = @dates.group_by {|f| f.created_at.beginning_of_year} %>
			<% @year.each do |year, other| %>
				<%= link_to "#{year.strftime("%Y")}", :action => "show_dates", :year => year.strftime("%Y") %>
				<% @month = other.group_by {|f| f.created_at.beginning_of_month} %>
				<% @month.each do |month, specific| %>
					<%= link_to "#{month.strftime('%B')}", :action => "show_dates", :year => "#{year.strftime("%Y")}", :month => month.strftime('%b') %>
				<% end %>
			<% end %>
		</div>
		<div class="widget-bottom"></div>
	</div>

app/views/good_reads/_form.html.erb
<%= form_for @post do |f| %>
   	<div class="full-width-clearer">
   		<%= f.label :title, "Title" %>
	   	<%= f.text_field :title %>
   	</div>

	<div class="full-width-clearer">
		<%= f.label :post, "Post" %>
	   	<%= f.text_area :post, :class => "mceEditor" %>	
	</div>
   	
  	<div class="full-width-clearer">
		<%= f.label :category, "Category" %>   
		<%= collection_select(:good_read, :category_id, Category.all, :id, :name, :prompt => true, :selected => params[:name]) %>
  	</div>
      
	<div class="full-width-clearer">
		<a href="http://bbd-images.bigblockdeals.com/image-manager" target="blank">Manage Images</a>
	</div>

<%= f.submit "Update", :disable_with => 'Updating...' %>
   
<% end %>

app/views/good_reads/create.html.erb
<h2>Blog Post</h2>

<%= render :partial => 'form' %>

app/views/good_reads/edit.html.erb
<!--
	TODO Add the Frame
-->
<div class="edit-page">
	<div class="topper"></div>
	<div class="main-content">
		<h2>Edit Blog Post</h2>

		<%= render :partial => 'form' %>
	</div>
	<div class="bottom"></div>
</div>

app/views/good_reads/index.html.erb
<div class="posts-container">
<div class="first-post">
	<div class="topper"></div>
		<div class="content-header">
			<img class="page-header" src="/images/good-reads-title.jpg"/>
		</div>
	<div class="bottom"></div>
		<div class="post-content">

<% if @posts.empty? %>
	<p>No Posts. Please check back soon. </p>
<% else %>

	<%= paginate @posts %>

	<% @posts.each do |f| %>

	<div class="regular-post">
		<div class="topper"></div>
		<div class="post-content">
		<h2><%= f.title %></h2>
		<div class="post-details">
			<p class="post-date"><%= special_date(f.created_at) %>&nbsp;&nbsp;|&nbsp;&nbsp;<p>
			<%= link_to "#{f.category.name}", :action => "show_categories", :id => f.category.name %><br>
		</div>


		<div class="post-text"> <%= shorten(f.post.html_safe) %> </div><br><br>

		<%= link_to "Read More", good_read_path(f.id), :class => 'read-more-link full-width-clearer' %>
		</div>
		<div class="bottom"></div>
	</div>

	<% end %>
<% end %>
</div>
</div>
</div>
</div>

app/views/good_reads/manage.html.erb
<div class="edit-page-wide">
	<div class="topper"></div>
	<div class="main-content">
		<h2>Manage BBD Blog</h2>
		<%= link_to "New Blog Post", new_good_read_path, :class => 'full-width-clearer' %>
		<div id="blog-post-previews">
			<h2 class="full-width-clearer">Blog Posts</h2>
			<% if @posts.empty? %>
				<p>No Posts. Please create a new one. </p>
			<% else %>
				<% @posts.each do |f| %>
				<div class="post-handle">
					<h2><%= f.title %></h2>
					<%= link_to "Edit This Post", edit_good_read_path(f.id) %><br><br>
					<%= link_to "Delete This Post", { :action => "destroy", :id => f.id }, :confirm => 'Are you sure?', :method => :delete %>
				</div>
				<% end %>
			<% end %>
		</div>
		<div id="category-previews">
			<h2>Blog Categories</h2>
			<%= link_to "New category", new_category_path, :class => "full-width-clearer" %>
			<% @categories.each do |c| %>
				<div class="indiv-category-preview full-width-clearer">
					<h2><%= c.name %></h2>
					<%= link_to "Edit", edit_category_path(c.id) %> 
					<%= link_to "Delete", { :action => "destroy", :id => c.id }, :confirm => 'Are you sure?', :method => :delete %>
				</div>
			<% end %>
		</div>
	</div>
	<div class="bottom"></div>
</div>

app/views/good_reads/new.html.erb
<div class="edit-page">
	<div class="topper"></div>
	<div class="main-content">
		<h2>New Blog Post</h2>

		<%= render :partial => 'form' %>
	</div>
	<div class="bottom"></div>
</div>

app/views/good_reads/show.html.erb
<!--
	TODO Needs to add style to the flash notices
-->
<p><%= flash.notice %></p><br>
<div class="posts-container">
	<div class="first-post">
	<div class="topper"></div>
		<div class="content-header">
			<img class="page-header" src="/images/good-reads-title.jpg"/>
			<%= link_to "Back to All Posts", good_reads_path, :class => "back-to-all-link" %>
		</div>
	<div class="bottom"></div>
	</div>
	<div class="regular-post">
		<div class="topper"></div>
		<div class="post-content">
			<% @post %>
			<h2><%= @post.title %></h2>
			<div class="post-details">
				<p class="post-date"><%= special_date(@post.created_at) %>&nbsp;&nbsp;|&nbsp;&nbsp;</p>
					<p class="post-date"><%= @post.category.name %></p>
			</div>



			<div class="post-text"> <%= @post.post.html_safe %></div>
			
			<% if session[:admin_id] %>
			<div class="post-admin-links">
				<%= link_to "Edit This Post", edit_good_read_path(@post.id) %><br><br>
				<%= link_to "Delete This Post", { :action => "destroy", :id => @post.id }, :confirm => 'Are you sure?', :method => :delete %>
			</div>

		<% end %>
		</div>
		<div class="bottom"></div>
	</div>
</div>
<div class="sidebar">
	<%= render 'layouts/widgets' %>
</div>

app/views/good_reads/show_categories.html.erb
<% if @posts.empty? %>
	<p>There are no posts in the <%= params[:id].capitalize %> category</p>
<% else %>
	  <div class="posts-container">
		<div class="first-post">
		<div class="topper"></div>
			<div class="content-header">
				<img class="page-header" src="/images/good-reads-title.jpg"/>
				<%= link_to "Back to All Posts", good_reads_path, :class => "back-to-all-link" %>
			</div>
		<div class="bottom"></div>
		</div>
	<% @posts.each do |f| %>

<div class="regular-post">
	<div class="topper"></div>
		<div class="post-content">
			<h2><%= f.title %></h2>
			<div class="post-details">
				<p class="post-date"><%= special_date(f.created_at) %>&nbsp;&nbsp;|&nbsp;&nbsp;</p>
				<% unless f.category.nil? %>
					<%= link_to "#{f.category.name}", :action => "show_categories", :id => f.category.name %>
				<% end %>
			</div>

			<div class="post-text"> <%= f.post.html_safe %> </div>
			
			<% unless session[:admin_id] %>
			<div class="post-admin-links">
				<%= link_to "Edit This Post", edit_good_read_path(f.id) %>
				<%= link_to "Delete This Post", { :action => "destroy", :id => f.id }, :confirm => 'Are you sure?', :method => :delete %>	
			</div>

		<% end %>
	</div>
	<div class="bottom"></div>
	</div>
	<% end %>
	</div>

<% end %>
<div class="sidebar">
	<%= render 'layouts/widgets' %>
</div>