config/routes.rb
Bigblockdeals::Application.routes.draw do

  resources :widget_types

  # This is for the Basic pages and their edit pages
  BASIC_CONTROLLERS.each do |f|
      get "#{f.last[:url].to_sym}/(:format)", :controller => "basics", :action => "#{f.first}", :as => f.last[:url]
      get "admin/#{f.last[:url].to_sym}/edit/(:id)(:format)", :controller => "basic_edits", :action => "#{f.first}", :as => "#{f.first}_edit"
      match "admin/#{f.last[:url].to_sym}/create/(:id)(:format)", :controller => "basic_edits", :action => "#{f.first}_create", :as => "#{f.first}_create"
  end
  match "business_inquires" => "business_leads#index"
  match "/business_leads/index" => "business_leads#index"

  root :to => "basics#current_deals"


  # This is for all the Good Reads
    get '/bbd-blog/' => "good_reads#index", :as => 'bbd_blog'
    get '/admin/bbd-blog/manage' => "good_reads#manage", :as => 'manage_bbd_blog'
    get '/admin/bbd-blog/new' => "good_reads#new", :as => "new_good_read"
    get '/admin/bbd-blog/:id/edit' => "good_reads#edit", :as => "edit_good_read"
    get '/bbd-blog/category/:id', :controller => 'good_reads', :action => 'show_categories', :as => "good_reads_category"
    match "/bbd-blog/date" => redirect("/bbd-blog") 
    get '/bbd-blog/date/(:year(/:month))', :controller => 'good_reads', :action => 'show_dates', :as => "good_reads_date"
    resources :good_reads
    
  # This is for all the Quotes

    
    scope "admin" do
      resources :quotes, :as => "quotes"
      resources :widgets, :as => "widgets"
      match 'widgets/move_dim_widgets' => 'widgets#move_dim_widgets', :as => :move_dim_widgets
      resources :categories, :as => "categories"
      resources :sessions, :as => "sessions"
      resources :spreadsheets, :as => "spreadsheets"
      resources :affiliates, :as => "affiliates"
      match 'affiliates/csv_import' => 'affiliates#csv_import'
      resources :customer_details, :as => 'customer_details'
      match 'customer_details/csv_import' => 'customer_details#csv_import'
      match 'widgets/manage' => 'widgets#index', :as => "manage_widgets"
      # resources :business_leads, :as => "business_leads"
    end
    
  #this is for all the Catagories for the good reads

  # This is for the Administration usage.
    resources :admins
    
  # This is for loggin in and out
    get '/admin/login' => 'sessions#new', :as => "login"
    get '/admin/logout' => 'sessions#destroy', :as => "logout"
    get "/admin/business_lead/:id" => "business_leads#show", :as => "admin_business_lead"
    get "/admin/business_leads/" => "business_leads#show_all", :as => "admin_business_leads"
    match '/admin/business_leads/destroy/:id' => 'business_leads#destroy'
    
end

app/models/category.rb
class Category < ActiveRecord::Base
  validates_presence_of :name
  has_many :good_reads
  accepts_nested_attributes_for :good_reads
  
  def self.list_names()
    @all = self.find(:all)
    hash = {}
    @all.each do |f|
      hash.merge!(f.name => f.id)
    end
    return hash
  end

end
# == Schema Information
#
# Table name: categories
#
#  id         :integer         not null, primary key
#  name       :string(255)
#  created_at :datetime
#  updated_at :datetime
#

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_filter :bomb_dot_com
  
  def index
    @categories = Category.all
    @title = "Catagories"
  end

  def edit
    @category = Category.find(params[:id])
    @title = "Edit category"
  end

  def new
    @category = Category.new
    @title = "new category"
  end

  def update
    @category = Category.find(params[:id])
    if @category.update_attributes(params[:category])
      redirect_to( categories_path, :notice => "category Updated" )
    else
      render :edit, :notice => "Error"
    end
  end

  def destroy
    @category = Category.find(params[:id])
    # Checks if there are any good_reads associated with the category.
    # FIXME Flash message needs to list all the blog entries in that category
    if @category.good_reads.count == 0
      if @category.destroy
        redirect_to categories_path, :notice => "category '#{@category.name}' Deleted."
      else
        render categories_path, :notice => "Well that was weird, #{@category.name} was not deleted..."
      end
    else
      a = []
      @good_reads = @category.good_reads.each do |f|
        a.concat(["#{f.title}"])
      end
      flash[:notice] = "The category was not deleted...Please remove all the Good Reads associated with this category."
      redirect_to categories_path
    end

  end

  def create
    @category = Category.new(params[:category])
    if @category.valid?
      @category.save
      redirect_to categories_path, :notice => "category created"
    else
      render :edit
    end
  end
end

app/views/categories/_form.html.erb
<% form_for @category do |f| -%>
<%= render "shared/error_messages", :target => @category %>
  <%= f.label :name, "Name" %>
  <%= f.text_field :name, :autofocus => :autofocus %>

<%= f.submit "Submit", :disable_with => 'Submiting...' %>
<% end -%>

app/views/categories/edit.html.erb
<h1>Edit this category!</h1>

<%= render :partial => 'form' %>

<%= link_to "Back", categories_path %>

app/views/categories/index.html.erb
<div class="edit-page">
	<div class="topper"></div>
	<div class="main-content">
			<h2>All the categories</h2>
			<% if @categories.nil? %>
				<p>there are no categories...</p><%= link_to "Add One", new_category_path %>
			<% else %>
			  <% @categories.each do |f| %>
				<div class="full-width-clearer">
					<p class="full-width-clearer"><%= f.name %></p>
					<%= link_to "Edit", edit_category_path(f.id) %> 
					<%= link_to "Delete", { :action => "destroy", :id => f.id }, :confirm => 'Are you sure?', :method => :delete %></p>					
				</div>
			  <% end %>
			<% end %>

			<%= link_to "New category", new_category_path %><br>
			<%= link_to "Back to Good Reads", good_reads_path() %>	
		</div>
	</div>
	<div class="bottom"></div>
</div>

app/views/categories/new.html.erb
<h1>Create a New category!</h1>

<%= render :partial => 'form' %>

<%= link_to "Back", categories_path %>