config/routes.rb
Bigblockdeals::Application.routes.draw do

  resources :widget_types

  # This is for the Basic pages and their edit pages
  BASIC_CONTROLLERS.each do |f|
      get "#{f.last[:url].to_sym}/(:format)", :controller => "basics", :action => "#{f.first}", :as => f.last[:url]
      get "admin/#{f.last[:url].to_sym}/edit/(:id)(:format)", :controller => "basic_edits", :action => "#{f.first}", :as => "#{f.first}_edit"
      match "admin/#{f.last[:url].to_sym}/create/(:id)(:format)", :controller => "basic_edits", :action => "#{f.first}_create", :as => "#{f.first}_create"
  end
  match "business_inquires" => "business_leads#index"
  match "/business_leads/index" => "business_leads#index"

  root :to => "basics#current_deals"


  # This is for all the Good Reads
    get '/bbd-blog/' => "good_reads#index", :as => 'bbd_blog'
    get '/admin/bbd-blog/manage' => "good_reads#manage", :as => 'manage_bbd_blog'
    get '/admin/bbd-blog/new' => "good_reads#new", :as => "new_good_read"
    get '/admin/bbd-blog/:id/edit' => "good_reads#edit", :as => "edit_good_read"
    get '/bbd-blog/category/:id', :controller => 'good_reads', :action => 'show_categories', :as => "good_reads_category"
    match "/bbd-blog/date" => redirect("/bbd-blog") 
    get '/bbd-blog/date/(:year(/:month))', :controller => 'good_reads', :action => 'show_dates', :as => "good_reads_date"
    resources :good_reads
    
  # This is for all the Quotes

    
    scope "admin" do
      resources :quotes, :as => "quotes"
      resources :widgets, :as => "widgets"
      match 'widgets/move_dim_widgets' => 'widgets#move_dim_widgets', :as => :move_dim_widgets
      resources :categories, :as => "categories"
      resources :sessions, :as => "sessions"
      resources :spreadsheets, :as => "spreadsheets"
      resources :affiliates, :as => "affiliates"
      match 'affiliates/csv_import' => 'affiliates#csv_import'
      resources :customer_details, :as => 'customer_details'
      match 'customer_details/csv_import' => 'customer_details#csv_import'
      match 'widgets/manage' => 'widgets#index', :as => "manage_widgets"
      # resources :business_leads, :as => "business_leads"
    end
    
  #this is for all the Catagories for the good reads

  # This is for the Administration usage.
    resources :admins
    
  # This is for loggin in and out
    get '/admin/login' => 'sessions#new', :as => "login"
    get '/admin/logout' => 'sessions#destroy', :as => "logout"
    get "/admin/business_lead/:id" => "business_leads#show", :as => "admin_business_lead"
    get "/admin/business_leads/" => "business_leads#show_all", :as => "admin_business_leads"
    match '/admin/business_leads/destroy/:id' => 'business_leads#destroy'
    
end

app/models/spreadsheet.rb
class Spreadsheet < ActiveRecord::Base
  has_attached_file :csv_spreadsheet
  validates_attachment_presence :csv_spreadsheet
  
  def self.gather_thine_spreadsheets
    spreadsheets = ["Affiliate", "CustomerDetail", "CustomersSummary", "DealDetail", "MerchantInformation", "Promotion"]
  end
  
end

# == Schema Information
#
# Table name: spreadsheets
#
#  id                           :integer         not null, primary key
#  table                        :string(255)
#  csv_spreadsheet_file_name    :string(255)
#  csv_spreadsheet_content_type :string(255)
#  csv_spreadsheet_file_size    :integer
#  csv_spreadsheet_updated_at   :datetime
#  created_at                   :datetime
#  updated_at                   :datetime
#

app/controllers/spreadsheets_controller.rb
class SpreadsheetsController < ApplicationController
  
  def index
    @title = "Spreadsheet Manager"
    
    # Push this over to the model
    hash = {}
    Spreadsheet.gather_thine_spreadsheets.each do |f|
      @last = ActiveRecord.const_get(f).last
      hash.merge!(f.to_sym => @last)
    end
    @hash = hash

    @current_jobs = Spreadsheet.all
  end
  
  def show
    if @model = ActiveRecord.const_get(params[:id])
      @title = "Spreadsheet | #{params[:id]}"
      @column_names = @model.list_columns
      @spreadsheet = @model.hashify
      
    else
      redirect_to :index, :notice => "This page does not exist"
    end
    rescue
      redirect_to spreadsheets_path, :notice => "This page does not exist"
  end

  def new
    @spreadsheet  = Spreadsheet.new
  end

  def create
    @spreadsheet = Spreadsheet.new(params[:spreadsheet])
    if @spreadsheet.valid?
      @spreadsheet.save
      Delayed::Job.enqueue(CsvImportingJob.new(@spreadsheet.id))
      redirect_to spreadsheets_path
    else
      render "new"
    end
  end
end

app/helpers/spreadsheets_helper.rb
module SpreadsheetsHelper
  
  def created_at_regardless(model_obj)
    unless model_obj.nil?
      @out = special_date(model_obj.created_at)
    else
      @out = "Not uploaded yet!"
    end
    return @out
  end
  
end

app/views/spreadsheets/index.html.erb
<div class="edit-page">
	<div class="topper"></div>
	<div class="main-content">
		<h2>List of current spreadsheets:</h2>
		<ul>
			<li class="spreadsheet-preview">
				<div class="majority-width">
					<p class="spreadsheet-name semi-bold-item full-width-clearer">Affiliates</p>
				</div>
				<div class="minor-width">
					<%= link_to "View", affiliates_path, :class => "spreadsheet-view-link" %>
				</div>
			</li>
			<li class="spreadsheet-preview">
				<div class="majority-width">
					<p class="spreadsheet-name semi-bold-item full-width-clearer">Customer Detail</p>
				</div>
				<div class="minor-width">
					<%= link_to "View", customer_details_path, :class => "spreadsheet-view-link" %>
				</div>
			</li>
			<li class="spreadsheet-preview">
				<div class="majority-width">
					<p class="spreadsheet-name semi-bold-item full-width-clearer">Customer Summaries</p>
				</div>
				<div class="minor-width">
					<a class="spreadsheet-view-link" href="#">View</a>
				</div>
			</li>
			<li class="spreadsheet-preview">
				<div class="majority-width">
					<p class="spreadsheet-name semi-bold-item full-width-clearer">Deal Details</p>
				</div>
				<div class="minor-width">
					<a class="spreadsheet-view-link" href="#">View</a>
				</div>
			</li>
			<li class="spreadsheet-preview">
				<div class="majority-width">
					<p class="spreadsheet-name semi-bold-item full-width-clearer">Merchant Information</p>
				</div>
				<div class="minor-width">
					<a class="spreadsheet-view-link" href="#">View</a>
				</div>
			</li>
			<li class="spreadsheet-preview">
				<div class="majority-width">
					<p class="spreadsheet-name semi-bold-item full-width-clearer">Promotions</p>
				</div>
				<div class="minor-width">
					<a class="spreadsheet-view-link" href="#">View</a>
				</div>
			</li>
		</ul>
	</div>
	<div class="bottom"></div>	
</div>

app/views/spreadsheets/new.html.erb
<h1>Spreadsheets#new</h1>
<p>Find me in app/views/spreadsheets/new.html.erb</p>

<% form_for @spreadsheet, :html => { :multipart => true } do |f| -%>
	<%= render "shared/error_messages", :target => @spreadsheet %>
	<%= f.label :csv_spreadsheet, "Spreadsheet" %><br>
	<%= f.file_field :csv_spreadsheet %>

	<%= f.label :table, "Affilitate", :value => :Affiliate %>
	<%= f.radio_button :table, :Affiliate %><br>
	<%= f.label :table, "Customer Detail", :value => :CustomerDetail %>
	<%= f.radio_button :table, :CustomerDetail %><br>
	<%= f.label :table, "Customer Summary", :value => :CustomerSummary %>
	<%= f.radio_button :table, :CustomersSummary %><br>
	<%= f.label :table, "Merchant Information", :value => :MerchantInformation %>
	<%= f.radio_button :table, :MerchantInformation %><br>
	<%= f.label :table, "Deal Detail", :value => :DealDetail %>
	<%= f.radio_button :table, :DealDetail %><br>
	<%= f.label :table, "Promotion", :value => :Promotion %>
	<%= f.radio_button :table, :Promotion %><br><br>

	<%= f.submit "Upload!", :disable_with => 'Uploading...' %>
<% end -%>

app/views/spreadsheets/show.html.erb
<div class="edit-page-wide">
	<div class="topper"></div>
	<div class="main-content">
		<h2>Promotions Spreadsheets</h2>
		<%= link_to "Upload", new_spreadsheet_path %>
		<%= link_to "Back", spreadsheets_path() %>


		<% if @spreadsheet.empty? %>
			No data has been uploaded or your data has not yet been processed.
		<% else %>
		<div class="spreadsheet-table">
			<table class="spreadsheet-viewer" cellspacing="15" cellpadding="5">
				<tr>
					<% @column_names.each do |f| %>
						<th><%= f %></th>
					<% end %>
				</tr>
				<% @spreadsheet.each do |f| %>
						<tr>
				        <% i = 0 %>
				        <% until i >= @column_names.count %>
				          <td><%= f.last[i] %></td>
							
				          <% i+=1 %>
	        			<% end %>
						</tr>
				    <% end %>
			</table>
		</div>
			
		<% end %>
	</div>
	<div class="bottom"></div>
</div>